name: Build Ghidra Extension

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Ghidra libraries
        run: |
          set -euxo pipefail
          GHIDRA_VERSION=11.3.2
          GHIDRA_BUILD=20250415
          GHIDRA_BASENAME="ghidra_${GHIDRA_VERSION}_PUBLIC"
          GHIDRA_ARCHIVE="${GHIDRA_BASENAME}_${GHIDRA_BUILD}.zip"
          curl -L "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${GHIDRA_VERSION}_build/${GHIDRA_ARCHIVE}" -o "$GHIDRA_ARCHIVE"
          mkdir -p lib
          unzip -q -j "$GHIDRA_ARCHIVE" \
            "${GHIDRA_BASENAME}/Ghidra/Features/Base/lib/Base.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Features/Decompiler/lib/Decompiler.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/Docking/lib/Docking.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/Generic/lib/Generic.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/Project/lib/Project.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/SoftwareModeling/lib/SoftwareModeling.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/Utility/lib/Utility.jar" \
            "${GHIDRA_BASENAME}/Ghidra/Framework/Gui/lib/Gui.jar" \
            -d lib
          rm "$GHIDRA_ARCHIVE"

      - name: Build extension
        run: mvn -B clean package assembly:single

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-extension
          path: target/GhidraMCP-*.zip
          if-no-files-found: error
